### ISSUE TITLE
multiple sizes of the same image

### ISSUE THREAD

**Issue by a-kolybelnikov** [nitin42/react-imgpro#5] opened 2017-12-08 15:06 UTC
Great piece of software!
How would I go about making three (... more) copies of different sizes of the same image? Before, for example, an s3 upload ... ?
Thanks!

**Comment by nitin42** [comment] 2017-12-08 17:25
Any idea how API could look like?

**Comment by akolybelnikov** [comment] 2017-12-09 11:34
1. user uploads an image with a file-upload.
2. ideally, at this point I would like to resize the image ( ...multiple sizes?)
3. I'm uploading the resized image(s) to s3.

At the moment, I cannot get hold of the uploaded file at all: I guess I need to pass a url to 'image', but I can't figure outwhat exactly the FileReader has to return.

**Comment by nitin42** [comment] 2017-12-09 12:41
FileReader returns an ArrayBuffer. You could create a blob url and then pass it as a prop the component and then apply the resize.

**Comment by nitin42** [comment] 2017-12-09 12:44
The component is monolithic but it doesn't have the power to reproduce the same effect on a number of images. You can use composition in your use case. 

Behind the scene, all operations are performed in series of chain on a single image. I'll see what I can do to support multiple images.

**Comment by akolybelnikov** [comment] 2017-12-14 21:48
I think my user case just requires a different functionality. I have implemented a serverless resize on the fly with AWS and it's all I need for the moment in terms of multiple versions of the same image for various screens. However, I will be playing around with your component a lot. How do you actually implement Jimp, in the front-end? I have tried using it before but encountered the 'no Buffer defined' issue, because it is something Node.js has natively and the front-end doesn't. Many thanks!

**Comment by nitin42** [comment] 2017-12-17 08:10
I am using Jimp by passing down the image source and image props via [this](https://github.com/nitin42/react-imgpro/blob/master/src/utils/options.js#L3) function and then processing the image with the Jimp instance (either in service worker or in main thread) via dependency injection.

**Comment by nitin42** [comment] 2018-01-05 12:39
Closing this because it relates to your business logic and not the library actually!

**Closed by nitin42** 2018-01-05 12:39 UTC
